// Code generated by goctl. DO NOT EDIT.
// Source: keystone.proto

package server

import (
	"context"

	"github.com/ScottCho/goweb/apps/keystone/rpc/internal/logic"
	"github.com/ScottCho/goweb/apps/keystone/rpc/internal/svc"
	"github.com/ScottCho/goweb/apps/keystone/rpc/pb/keystone"
)

type KeystoneServer struct {
	svcCtx *svc.ServiceContext
	keystone.UnimplementedKeystoneServer
}

func NewKeystoneServer(svcCtx *svc.ServiceContext) *KeystoneServer {
	return &KeystoneServer{
		svcCtx: svcCtx,
	}
}

func (s *KeystoneServer) Login(ctx context.Context, in *keystone.LoginRequest) (*keystone.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *KeystoneServer) Register(ctx context.Context, in *keystone.RegisterRequest) (*keystone.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *KeystoneServer) UserInfo(ctx context.Context, in *keystone.UserInfoRequest) (*keystone.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
